pipelines:
  # Run pipelines on a given branch. See https://confluence.atlassian.com/bitbucket/branch-workflows-856697482.html
  # Deployment command has additional options. Please consult README.md
  branches:
    master:       
      - step:
          name: "Deploy to Production"
          image: atlassian/default-image:2
          script:
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: "USERNAME"
                SERVER: "0.0.0.0"
                PORT: "22"
                COMMAND: "cd domain.ch && ./nn/docker-prod/deploy.sh"

      #    name: Test E2E playwright
      #    image: mcr.microsoft.com/playwright:v1.28.0-focal
      #    script:
      #      - cd playwright
      #      - npm install
      #      - npx playwright install
      #      - npx playwright test
