version: '3'

dotenv: ['.env', '.infrastructure']

tasks:
  default:
    desc: Lists all available tasks
    cmds:
      - task -l

  # "SSH into"
  # "SSH into"
  nn-ssh-prod:
    desc: SSH into the production server
    aliases: [prod]
    cmds:
      - ssh -t $DOCKER_PROD_USER@$DOCKER_PROD_HOST "cd $DOCKER_PROD_DOCKER_PATH; exec \$SHELL -l"
    interactive: true

  nn-ssh-prod-root:
    desc: SSH into the production server
    aliases: [prod-root]
    cmds:
      - ssh -t root@$DOCKER_PROD_HOST "cd $DOCKER_PROD_DOCKER_PATH; exec \$SHELL -l"
    interactive: true

  nn-ssh-stage:
    desc: SSH into the stage server
    aliases: [stage]
    cmds:
      - ssh -t $DOCKER_STAGE_USER@$DOCKER_STAGE_HOST "cd $DOCKER_STAGE_DOCKER_PATH; exec \$SHELL -l"
    interactive: true

  nn-ssh-stage-root:
    desc: SSH into the stage server
    aliases: [stage-root]
    cmds:
      - ssh -t root@$DOCKER_STAGE_HOST "cd $DOCKER_STAGE_DOCKER_PATH; exec \$SHELL -l"
    interactive: true

  # Docker commands (usually used on servers)
  nn-docker-prod-bash:
    desc: Opens a bash shell in the Frontend Docker container
    cmds:
      - docker compose exec -it frontend bash
    interactive: true

  open-hostinginfo:
    desc: Open google doc with info about open-hostinginfo
    cmds:
      - open tbd

  # "Local development helpers"
  run-playwright:
    desc: Run playwright tests (cd playwright && npm test)
    cmds:
      - cd playwright && npm test
    interactive: true

  # Open commands
  open-bitbucket:
    desc: Opens the Bitbucket repository in the default browser
    cmds:
      - open $BITBUCKET_URL