export const siteConfig = {
  title: 'Next.js Starter',
  description: 'Generated by nn-nextjs-starter',
  shortUrl: 'example.ch',
  url: process.env.NEXT_PUBLIC_FRONTEND_BASE_URL,
  ogImage: '/images/example.jpg',
  themeColor: '#ffffff',
  googleAnalyticsId: '',
};
